"""sweetbear-edge: a calibrated probability and edge-detection engine."""

from .backtest import (
    BacktestResult,
    Bet,
    flat_stake,
    kelly_stake,
    percent_bankroll,
    run_backtest,
    walk_forward_calibrate,
)
from .calibration import (
    BrierDecomposition,
    IsotonicCalibrator,
    PlattScaler,
    ReliabilityCurve,
    brier_decomposition,
    brier_score,
    expected_calibration_error,
    log_loss,
    maximum_calibration_error,
    reliability_curve,
)
from .margin import devig, devig_probabilities, power_exponent, shin_z
from .edge import (
    breakeven_probability,
    closing_line_value,
    expected_value,
    fractional_kelly,
    growth_rate,
    kelly_fraction,
    shrink_toward_market,
    simultaneous_kelly,
)
from .significance import (
    SignificanceResult,
    cluster_bootstrap_ci,
    clustered_significance,
    deflate_t_statistic,
    design_effect,
    detectable_edge,
    effective_sample_size,
    intracluster_correlation,
    multiple_testing_threshold,
    required_sample_size,
)
from .odds import (
    american_to_decimal,
    american_to_implied,
    decimal_to_american,
    decimal_to_fractional,
    decimal_to_implied,
    fractional_to_decimal,
    implied_to_american,
    implied_to_decimal,
    overround,
    vig,
)

__version__ = "0.1.0"

__all__ = [
    "american_to_decimal",
    "american_to_implied",
    "decimal_to_american",
    "decimal_to_fractional",
    "decimal_to_implied",
    "fractional_to_decimal",
    "implied_to_american",
    "implied_to_decimal",
    "overround",
    "vig",
    "devig",
    "devig_probabilities",
    "power_exponent",
    "shin_z",
    "brier_score",
    "log_loss",
    "brier_decomposition",
    "BrierDecomposition",
    "reliability_curve",
    "ReliabilityCurve",
    "expected_calibration_error",
    "maximum_calibration_error",
    "PlattScaler",
    "IsotonicCalibrator",
    "expected_value",
    "breakeven_probability",
    "kelly_fraction",
    "fractional_kelly",
    "shrink_toward_market",
    "simultaneous_kelly",
    "closing_line_value",
    "growth_rate",
    "Bet",
    "BacktestResult",
    "run_backtest",
    "flat_stake",
    "percent_bankroll",
    "kelly_stake",
    "walk_forward_calibrate",
    "SignificanceResult",
    "clustered_significance",
    "cluster_bootstrap_ci",
    "intracluster_correlation",
    "design_effect",
    "effective_sample_size",
    "required_sample_size",
    "detectable_edge",
    "multiple_testing_threshold",
    "deflate_t_statistic",
]
